// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTv8qIkorg108HTJjs2CE3n2tsdNnLVA8',
    appId: '1:815399387398:web:bb0ab6c32a736dc8aa1e87',
    messagingSenderId: '815399387398',
    projectId: 'vault-2029f',
    authDomain: 'vault-2029f.firebaseapp.com',
    storageBucket: 'vault-2029f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlUz3KbcUb0WvmgGMl9J4c6NofKl71jJ0',
    appId: '1:815399387398:android:f8f261f4f5e77d0baa1e87',
    messagingSenderId: '815399387398',
    projectId: 'vault-2029f',
    storageBucket: 'vault-2029f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeHoUIj9_OqGa_IItlnhmQRWTUTFYbTyA',
    appId: '1:815399387398:ios:1965ff7e0c9b3b56aa1e87',
    messagingSenderId: '815399387398',
    projectId: 'vault-2029f',
    storageBucket: 'vault-2029f.appspot.com',
    iosClientId: '815399387398-ks3dkpc97mtbrtduaf8a5eat9hp72hgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.vault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeHoUIj9_OqGa_IItlnhmQRWTUTFYbTyA',
    appId: '1:815399387398:ios:1965ff7e0c9b3b56aa1e87',
    messagingSenderId: '815399387398',
    projectId: 'vault-2029f',
    storageBucket: 'vault-2029f.appspot.com',
    iosClientId: '815399387398-ks3dkpc97mtbrtduaf8a5eat9hp72hgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.vault',
  );
}
